ALTER TABLE users ALTER COLUMN user_guid DROP DEFAULT;
ALTER TABLE users ALTER COLUMN role DROP DEFAULT;
ALTER TABLE users ALTER COLUMN member_rank DROP DEFAULT;
ALTER TABLE users ALTER COLUMN active DROP DEFAULT;

ALTER TABLE hotels ALTER COLUMN hotel_guid DROP DEFAULT;
ALTER TABLE hotels ALTER COLUMN status DROP DEFAULT;

ALTER TABLE rooms ALTER COLUMN room_guid DROP DEFAULT;
ALTER TABLE rooms ALTER COLUMN status DROP DEFAULT;
ALTER TABLE rooms ALTER COLUMN price DROP DEFAULT;

ALTER TABLE images ALTER COLUMN image_guid DROP DEFAULT;

ALTER TABLE bookings ALTER COLUMN booking_guid DROP DEFAULT;
ALTER TABLE bookings ALTER COLUMN price DROP DEFAULT;
ALTER TABLE bookings ALTER COLUMN status DROP DEFAULT;
